const ar = {
  nav: { dashboard: "لوحة القيادة", sales: "المبيعات", projects: "المشاريع", procurement: "المشتريات", production: "الإنتاج", finance: "المالية", hr: "الموارد البشرية", engineering: "الهندسة", customerService: "خدمة العملاء", aiChat: "المساعد الذكي" },
  common: { appName: "إدارة التصنيع", appDescription: "نظام إدارة لصناعة الألمنيوم والزجاج والـ UPVC والواجهات والـ ACP", new: "جديد", save: "حفظ", cancel: "إلغاء", delete: "حذف", edit: "تعديل", view: "عرض", back: "رجوع", search: "بحث", noData: "لا توجد بيانات", loading: "جارٍ التحميل...", total: "المجموع", status: "الحالة", actions: "إجراءات", email: "البريد الإلكتروني", phone: "الهاتف", notes: "ملاحظات", select: "اختر...", none: "بدون", price: "السعر", subtotal: "المجموع الفرعي", discount: "الخصم", taxRate: "نسبة الضريبة (%)", unitPrice: "سعر الوحدة", viewAll: "عرض الكل", printPDF: "طباعة / PDF", validUntil: "صالح حتى", additionalNotes: "ملاحظات إضافية", addItem: "+ إضافة صنف", taxWithRate: "الضريبة ({rate}%)", assignedTo: "مسند إلى", created: "تاريخ الإنشاء", result: "النتيجة", unknown: "غير معروف", error: "حدث خطأ", address: "العنوان", description: "الوصف", english: "English", arabic: "العربية", priority: { low: "منخفض", medium: "متوسط", high: "عالي", urgent: "عاجل" } },
  dashboard: { title: "لوحة القيادة التنفيذية", leads: "العملاء المتوقعون", projects: "المشاريع", pos: "أوامر الشراء", production: "الإنتاج", expenses: "المصروفات", tickets: "التذاكر", employees: "الموظفين", drawings: "الرسومات", inventory: "المخزون", recentLeads: "آخر العملاء", recentTickets: "آخر التذاكر", leadsWon: "فوز", total: "إجمالي", openPOs: "أوامر شراء مفتوحة", transactions: "معاملة", openTickets: "تذاكر مفتوحة", presentToday: "موجود اليوم", emptyItems: "فارغ", monthlyExpenses: "مصروفات الشهر" },
  sales: { pipeline: "خط أنابيب المبيعات", newLead: "عميل متوقع جديد", companyName: "اسم الشركة", contactName: "اسم جهة الاتصال", stage: "المرحلة", score: "التقييم", estimatedValue: "القيمة التقديرية", source: "المصدر", quotation: "عرض سعر", newQuotation: "عرض سعر جديد", stageLead: "جديد", stageQualified: "مؤهل", stageQuotation: "عرض سعر", stageNegotiation: "تفاوض", stageWon: "فوز", stageLost: "خسارة", sourceWebsite: "موقع إلكتروني", sourceReferral: "إحالة", sourceCall: "اتصال هاتفي", sourceWalkin: "زيارة", sourceExhibition: "معرض", createLead: "إنشاء عميل", moveToStage: "نقل إلى مرحلة", noLeads: "لا يوجد عملاء متوقعون بعد.", noQuotations: "لا توجد عروض سعر بعد.", client: "العميل", projectTypePlaceholder: "نوع المشروع (مثال: نافذة)", dimensionsPlaceholder: "الأبعاد (مثال: 1.2×1.5م)", materialPlaceholder: "المادة (مثال: ألمنيوم)", createQuotation: "إنشاء عرض سعر", generateItems: "توليد الأصناف", generating: "جارٍ التوليد..." },
  production: { workOrders: "أوامر العمل", newOrder: "أمر إنتاج جديد", productName: "اسم المنتج", quantity: "الكمية", priority: "الأولوية", qualityCheck: "فحص الجودة", recordCheck: "تسجيل فحص", statusPending: "معلق", statusInProgress: "قيد التنفيذ", statusCompleted: "مكتمل", statusCancelled: "ملغي", scheduled: "مجدول", completed: "تاريخ الإكمال", markInProgress: "تعيين قيد التنفيذ", markCompleted: "تعيين مكتمل", stage: "المرحلة", stagePlaceholder: "مثال: قص، تجميع، تشطيب", passed: "ناجح", failed: "راسب", noQualityChecks: "لا توجد فحوصات جودة مسجلة بعد.", scheduledDate: "التاريخ المجدول", projectOptional: "المشروع (اختياري)", createOrder: "إنشاء أمر إنتاج" },
  finance: { expenses: "المصروفات", newExpense: "مصروف جديد", category: "التصنيف", description: "الوصف", amount: "المبلغ", monthlyExpenses: "مصروفات الشهر", totalExpenses: "إجمالي المصروفات", categories: "التصنيفات", transactions: "المعاملات", byCategory: "حسب التصنيف", allExpenses: "كل المصروفات", noExpenses: "لا توجد مصروفات مسجلة.", categoryPlaceholder: "مثال: مواد، عمالة، نقل", projectOptional: "المشروع (اختياري)", receiptUrl: "رابط الإيصال (اختياري)", addExpense: "إضافة مصروف", receipt: "الإيصال" },
  hr: { attendance: "الحضور والانصراف", recordAttendance: "تسجيل حضور", employee: "الموظف", date: "التاريخ", present: "حاضر", absent: "غائب", late: "متأخر", leave: "إجازة", totalEmployees: "إجمالي الموظفين", presentToday: "الموجودون اليوم", totalRecords: "إجمالي السجلات", recentAttendance: "آخر الحضور", noRecords: "لا توجد سجلات بعد.", checkIn: "وقت الحضور", checkOut: "وقت الانصراف", saveAttendance: "حفظ الحضور", attendanceRecord: "سجل الحضور" },
  engineering: { drawings: "الرسومات الهندسية", uploadDrawing: "رفع رسمة", title: "العنوان", version: "الإصدار", totalDrawings: "إجمالي الرسومات", projectsWithDrawings: "مشاريع برسومات", noDrawings: "لا توجد رسومات مرفوعة.", titlePlaceholder: "مثال: واجهة المبنى - القسم أ", fileUrl: "رابط الملف", urlPlaceholder: "https://...", openDrawing: "فتح الرسمة" },
  customerService: { tickets: "تذاكر الدعم", newTicket: "تذكرة جديدة", subject: "الموضوع", customerName: "اسم العميل", open: "مفتوحة", resolved: "تم الحل", inProgress: "قيد المعالجة", noTickets: "لا توجد تذاكر بعد.", categoryInstallation: "تركيب", categoryQuality: "مشكلة جودة", categoryMaintenance: "صيانة", categoryBilling: "فوترة", categoryOther: "أخرى", relatedProject: "المشروع المرتبط (اختياري)", createTicket: "إنشاء تذكرة", updateStatus: "تحديث الحالة", actionStart: "بدء المعالجة", actionResolve: "حل", actionClose: "إغلاق", actionReopen: "إعادة فتح", resolvedOn: "تم الحل في" },
  ai: { analyze: "تحليل بالذكاء الاصطناعي", generate: "توليد بالذكاء الاصطناعي", chat: "المساعد الذكي", ask: "اسألني عن المنتجات أو العمليات أو المشاريع...", generateQuotation: "توليد عرض سعر بالذكاء الاصطناعي", reanalyze: "إعادة التحليل", send: "إرسال", greeting: "مرحباً! أنا المساعد الذكي لنظام إدارة التصنيع. كيف يمكنني مساعدتك اليوم؟" },
  auth: { email: "البريد الإلكتروني", password: "كلمة المرور", signIn: "تسجيل الدخول", invalidCredentials: "بيانات الدخول غير صحيحة", english: "English", arabic: "العربية" },
  projects: { newProject: "مشروع جديد", projectName: "اسم المشروع", clientName: "اسم العميل", clientPhone: "هاتف العميل", location: "الموقع", startDate: "تاريخ البداية", endDate: "تاريخ النهاية", budget: "الميزانية", actualCost: "التكلفة الفعلية", projectManager: "مدير المشروع", create: "إنشاء مشروع", noProjects: "لا توجد مشاريع بعد.", tasks: "مهام ({count})", reports: "تقارير ({count})", tasksSection: "المهام", addTask: "+ إضافة مهمة", noTasks: "لا توجد مهام بعد.", due: "تاريخ الاستحقاق", dailyReports: "التقارير اليومية", dailyReport: "تقرير يومي", newReport: "+ تقرير جديد", noReports: "لا توجد تقارير بعد.", delays: "التأخيرات", summary: "الملخص", weather: "الطقس", weatherPlaceholder: "مثال: مشمس، ٣٥°م", delaysPlaceholder: "هل توجد تأخيرات؟", submitReport: "إرسال التقرير", newTask: "مهمة جديدة", dueDate: "تاريخ الاستحقاق", createTask: "إنشاء مهمة", label: "المشروع", pos: "أوامر الشراء", productionOrders: "أوامر الإنتاج", tickets: "التذاكر", statusPlanning: "تخطيط", statusInProgress: "قيد التنفيذ", statusOnHold: "معلق", statusCompleted: "مكتمل", statusCancelled: "ملغي" },
  procurement: { newPO: "+ أمر شراء جديد", noPOs: "لا توجد أوامر شراء.", suppliers: "الموردون", addSupplier: "+ إضافة مورد", noSuppliers: "لا توجد موردين.", newSupplier: "مورد جديد", supplier: "المورد", projectOptional: "المشروع (اختياري)", itemsJSON: "الأصناف (صيغة JSON)", expectedDelivery: "تاريخ التسليم المتوقع", createPO: "إنشاء أمر شراء" },
  inventory: { addItem: "+ إضافة صنف", noItems: "لا توجد أصناف في المخزون.", newItem: "صنف مخزون جديد", sku: "رمز الصنف (SKU)", unit: "الوحدة", itemName: "اسم الصنف", minQuantity: "الحد الأدنى للكمية", unitCost: "تكلفة الوحدة (SAR)", pcs: "قطعة", m: "متر", sqm: "متر مربع", kg: "كيلوجرام", roll: "لفة", categoryAluminum: "ألمنيوم", categoryGlass: "زجاج", categoryUpvc: "UPVC", categoryHardware: "مستلزمات", categoryAcp: "ACP", categoryConsumable: "مستهلكات" },
};
export type Translations = typeof ar;
export default ar;
