import type { Translations } from "./ar";

const en: Translations = {
  nav: { dashboard: "Dashboard", sales: "Sales", projects: "Projects", procurement: "Procurement", production: "Production", finance: "Finance", hr: "HR", engineering: "Engineering", customerService: "Customer Service", aiChat: "AI Chat" },
  common: { appName: "ERP Manufacturing", appDescription: "Management system for aluminum, glass, UPVC, curtain wall & ACP", new: "New", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", view: "View", back: "Back", search: "Search", noData: "No data", loading: "Loading...", total: "Total", status: "Status", actions: "Actions", email: "Email", phone: "Phone", notes: "Notes", select: "Select...", none: "None", price: "Price", subtotal: "Subtotal", discount: "Discount", taxRate: "Tax Rate (%)", unitPrice: "Unit Price", viewAll: "View all", printPDF: "Print / PDF", validUntil: "Valid until", additionalNotes: "Additional notes", addItem: "+ Add item", taxWithRate: "Tax ({rate}%)", assignedTo: "Assigned To", created: "Created", result: "Result", unknown: "Unknown", error: "An error occurred", address: "Address", description: "Description", english: "English", arabic: "العربية", priority: { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" } },
  dashboard: { title: "Executive Dashboard", leads: "Leads", projects: "Projects", pos: "Purchase Orders", production: "Production", expenses: "Expenses", tickets: "Tickets", employees: "Employees", drawings: "Drawings", inventory: "Inventory", recentLeads: "Recent Leads", recentTickets: "Recent Tickets", leadsWon: "won", total: "total", openPOs: "Open POs", transactions: "txns", openTickets: "Open Tickets", presentToday: "today", emptyItems: "empty", monthlyExpenses: "Monthly Expenses" },
  sales: { pipeline: "Sales Pipeline", newLead: "New Lead", companyName: "Company Name", contactName: "Contact Name", stage: "Stage", score: "Score", estimatedValue: "Estimated Value", source: "Source", quotation: "Quotation", newQuotation: "New Quotation", stageLead: "New Lead", stageQualified: "Qualified", stageQuotation: "Quotation", stageNegotiation: "Negotiation", stageWon: "Won", stageLost: "Lost", sourceWebsite: "Website", sourceReferral: "Referral", sourceCall: "Phone Call", sourceWalkin: "Walk-in", sourceExhibition: "Exhibition", createLead: "Create Lead", moveToStage: "Move to Stage", noLeads: "No leads yet.", noQuotations: "No quotations yet.", client: "Client", projectTypePlaceholder: "Project type (e.g. Window)", dimensionsPlaceholder: "Dimensions (e.g. 1.2x1.5m)", materialPlaceholder: "Material (e.g. Aluminum)", createQuotation: "Create Quotation", generateItems: "Generate Items", generating: "Generating..." },
  production: { workOrders: "Work Orders", newOrder: "New Production Order", productName: "Product Name", quantity: "Quantity", priority: "Priority", qualityCheck: "Quality Check", recordCheck: "Record Check", statusPending: "Pending", statusInProgress: "In Progress", statusCompleted: "Completed", statusCancelled: "Cancelled", scheduled: "Scheduled", completed: "Completed", markInProgress: "Mark In Progress", markCompleted: "Mark Completed", stage: "Stage", stagePlaceholder: "e.g. Cutting, Assembly, Finishing", passed: "Passed", failed: "Failed", noQualityChecks: "No quality checks recorded yet.", scheduledDate: "Scheduled Date", projectOptional: "Project (optional)", createOrder: "Create Production Order" },
  finance: { expenses: "Expenses", newExpense: "New Expense", category: "Category", description: "Description", amount: "Amount", monthlyExpenses: "Monthly Expenses", totalExpenses: "Total Expenses", categories: "Categories", transactions: "Transactions", byCategory: "By Category", allExpenses: "All Expenses", noExpenses: "No expenses recorded.", categoryPlaceholder: "e.g. Materials, Labor, Transport", projectOptional: "Project (optional)", receiptUrl: "Receipt URL (optional)", addExpense: "Add Expense", receipt: "Receipt" },
  hr: { attendance: "HR & Attendance", recordAttendance: "Record Attendance", employee: "Employee", date: "Date", present: "Present", absent: "Absent", late: "Late", leave: "On Leave", totalEmployees: "Total Employees", presentToday: "Present Today", totalRecords: "Total Records", recentAttendance: "Recent Attendance", noRecords: "No records yet.", checkIn: "Check In", checkOut: "Check Out", saveAttendance: "Save Attendance", attendanceRecord: "Attendance Record" },
  engineering: { drawings: "Engineering Drawings", uploadDrawing: "Upload Drawing", title: "Title", version: "Version", totalDrawings: "Total Drawings", projectsWithDrawings: "Projects with Drawings", noDrawings: "No drawings uploaded.", titlePlaceholder: "e.g. Facade Elevation - Section A", fileUrl: "File URL", urlPlaceholder: "https://...", openDrawing: "Open Drawing" },
  customerService: { tickets: "Support Tickets", newTicket: "New Ticket", subject: "Subject", customerName: "Customer Name", open: "Open", resolved: "Resolved", inProgress: "In Progress", noTickets: "No tickets yet.", categoryInstallation: "Installation", categoryQuality: "Quality Issue", categoryMaintenance: "Maintenance", categoryBilling: "Billing", categoryOther: "Other", relatedProject: "Related Project (optional)", createTicket: "Create Ticket", updateStatus: "Update Status", actionStart: "Start Progress", actionResolve: "Resolve", actionClose: "Close", actionReopen: "Reopen", resolvedOn: "Resolved on" },
  ai: { analyze: "Analyze with AI", generate: "Generate with AI", chat: "AI Chat", ask: "Ask me anything about products, processes, or projects...", generateQuotation: "Generate Quotation with AI", reanalyze: "Re-analyze", send: "Send", greeting: "Hello! I'm the ERP Manufacturing AI assistant. How can I help you today?" },
  auth: { email: "Email", password: "Password", signIn: "Sign in", invalidCredentials: "Invalid credentials", english: "English", arabic: "العربية" },
  projects: { newProject: "New Project", projectName: "Project Name", clientName: "Client Name", clientPhone: "Client Phone", location: "Location", startDate: "Start Date", endDate: "End Date", budget: "Budget", actualCost: "Actual Cost", projectManager: "PM", create: "Create Project", noProjects: "No projects yet.", tasks: "{count} tasks", reports: "{count} reports", tasksSection: "Tasks", addTask: "+ Add Task", noTasks: "No tasks yet.", due: "Due", dailyReports: "Daily Reports", dailyReport: "Daily Report", newReport: "+ New Report", noReports: "No reports yet.", delays: "Delays", summary: "Summary", weather: "Weather", weatherPlaceholder: "e.g. Sunny, 35°C", delaysPlaceholder: "Any delays?", submitReport: "Submit Report", newTask: "New Task", dueDate: "Due Date", createTask: "Create Task", label: "Project", pos: "POs", productionOrders: "Prod Orders", tickets: "Tickets", statusPlanning: "Planning", statusInProgress: "In Progress", statusOnHold: "On Hold", statusCompleted: "Completed", statusCancelled: "Cancelled" },
  procurement: { newPO: "+ New PO", noPOs: "No purchase orders.", suppliers: "Suppliers", addSupplier: "+ Add Supplier", noSuppliers: "No suppliers.", newSupplier: "New Supplier", supplier: "Supplier", projectOptional: "Project (optional)", itemsJSON: "Items (JSON format)", expectedDelivery: "Expected Delivery", createPO: "Create Purchase Order" },
  inventory: { addItem: "+ Add Item", noItems: "No inventory items.", newItem: "New Inventory Item", sku: "SKU", unit: "Unit", itemName: "Item Name", minQuantity: "Min Quantity", unitCost: "Unit Cost (SAR)", pcs: "Pieces", m: "Meters", sqm: "Square Meters", kg: "Kilograms", roll: "Roll", categoryAluminum: "Aluminum", categoryGlass: "Glass", categoryUpvc: "UPVC", categoryHardware: "Hardware", categoryAcp: "ACP", categoryConsumable: "Consumable" },
};
export default en;
